<?php

namespace Stone256\CookBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * cookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cookingRepository extends EntityRepository
{
}
