<?php

namespace Stone256\CookBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * recipesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class recipesRepository extends EntityRepository
{
}
